version: '3'
services:
  nextjs-app:
    container_name: nextjs-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile  # Use the Dockerfile for Node.js 18
    ports:
      - "12300:3000"  # Map port 3000 from the container to your host
    environment:
      - NODE_ENV=production
